### ISSUE TITLE
Execution error: Cannot read property 'enabled' of undefined

### ISSUE THREAD

**Issue by tobilg** [DavidWells/serverless-manifest-plugin#15]
There's an error when using the latest version with no custom configuration specified in the `serverless.yml`:

```javascript
 TypeError: Cannot read property 'enabled' of undefined
      at hasCustomDomain (/service/node_modules/serverless-manifest-plugin/src/index.js:486:67)
      at Object.keys.reduce.urls.apiGateway (/service/node_modules/serverless-manifest-plugin/src/index.js:212:26)
      at Array.reduce (<anonymous>)
      at getFormattedData (/service/node_modules/serverless-manifest-plugin/src/index.js:198:52)
```

It seems it assumes that the customDomain plugin is present: https://github.com/DavidWells/serverless-manifest-plugin/blob/master/src/index.js#L486

**Comment by DavidWells** [comment]
Fixes via `serverless-manifest-plugin@1.0.6`
