### ISSUE TITLE
manifest not working with provisionedConcurrency

### ISSUE THREAD

**Issue by orr-levinger** [DavidWells/serverless-manifest-plugin#20]
it seems that the plugin is not working with the provisionedConcurrency property..

```
  Error: File "src/functions/static/get-genders.js" not found. /Users/orrlevinger/projects/BlindChat/blind-chat-backend/src/functions/static/get-genders.js missing
      at getFunctionPath (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/serverless-manifest-plugin/src/index.js:535:11)
      at Object.keys.reduce.urls.apiGateway (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/serverless-manifest-plugin/src/index.js:317:30)
      at Array.reduce (<anonymous>)
      at getFormattedData (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/serverless-manifest-plugin/src/index.js:213:52)
      at /Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/serverless-manifest-plugin/src/index.js:85:30
      at tryCatcher (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
```

  getGenders:
    handler: src/functions/static/get-genders.handler
    provisionedConcurrency: 5

all other functions works..

**Comment by DavidWells** [comment]
If you are using typescript you want to use the `srcPath` option https://github.com/DavidWells/serverless-manifest-plugin/pull/18/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R44

This should resolve the file

- https://github.com/DavidWells/serverless-manifest-plugin/pull/18

**Comment by orr-levinger** [comment]
Not sure i understand what you mean by that..
where to use srcPath
